# Generated by Django 5.0.6 on 2024-06-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_menuimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='nutritional_info',
            field=models.TextField(help_text='Use HTML tags to format the content'),
        ),
    ]
