# Generated by Django 5.0.6 on 2024-06-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_menu_nutritional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(help_text='Use HTML tags to format the content'),
        ),
    ]
