# Generated by Django 5.0.6 on 2024-06-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blogpost_created_at_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_gallery',
            field=models.BooleanField(default=False),
        ),
    ]
